/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppBoardRouteImport } from './routes/_app.board'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppDailyRouteImport } from './routes/_app.daily'
import { Route as AppReviewRouteImport } from './routes/_app.review'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppShopRouteImport } from './routes/_app.shop'
import { Route as AppStatsRouteImport } from './routes/_app.stats'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnswersRouteImport } from './routes/admin/answers'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminLanguagesRouteImport } from './routes/admin/languages'
import { Route as AdminLessonsRouteImport } from './routes/admin/lessons'
import { Route as AdminQuestionsRouteImport } from './routes/admin/questions'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminVocabularyRouteImport } from './routes/admin/vocabulary'
import { Route as LessonIdRouteImport } from './routes/lesson.$id'
import { Route as AppCategoryIdRouteImport } from './routes/_app.category.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardRoute = AppBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppDailyRoute = AppDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppShopRoute = AppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnswersRoute = AdminAnswersRouteImport.update({
  id: '/answers',
  path: '/answers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLanguagesRoute = AdminLanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLessonsRoute = AdminLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminVocabularyRoute = AdminVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LessonIdRoute = LessonIdRouteImport.update({
  id: '/lesson/$id',
  path: '/lesson/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCategoryIdRoute = AppCategoryIdRouteImport.update({
  id: '/category/$id',
  path: '/category/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/': typeof AppIndexRoute
  '/board': typeof AppBoardRoute
  '/chat': typeof AppChatRoute
  '/daily': typeof AppDailyRoute
  '/review': typeof AppReviewRoute
  '/settings': typeof AppSettingsRoute
  '/shop': typeof AppShopRoute
  '/stats': typeof AppStatsRoute
  '/admin/answers': typeof AdminAnswersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vocabulary': typeof AdminVocabularyRoute
  '/lesson/$id': typeof LessonIdRoute
  '/admin/': typeof AdminIndexRoute
  '/category/$id': typeof AppCategoryIdRoute
}
export interface FileRoutesByTo {
  '/board': typeof AppBoardRoute
  '/chat': typeof AppChatRoute
  '/daily': typeof AppDailyRoute
  '/review': typeof AppReviewRoute
  '/settings': typeof AppSettingsRoute
  '/shop': typeof AppShopRoute
  '/stats': typeof AppStatsRoute
  '/admin/answers': typeof AdminAnswersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vocabulary': typeof AdminVocabularyRoute
  '/lesson/$id': typeof LessonIdRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/category/$id': typeof AppCategoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/_app/board': typeof AppBoardRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/daily': typeof AppDailyRoute
  '/_app/review': typeof AppReviewRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/shop': typeof AppShopRoute
  '/_app/stats': typeof AppStatsRoute
  '/admin/answers': typeof AdminAnswersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vocabulary': typeof AdminVocabularyRoute
  '/lesson/$id': typeof LessonIdRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/category/$id': typeof AppCategoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/'
    | '/board'
    | '/chat'
    | '/daily'
    | '/review'
    | '/settings'
    | '/shop'
    | '/stats'
    | '/admin/answers'
    | '/admin/categories'
    | '/admin/languages'
    | '/admin/lessons'
    | '/admin/questions'
    | '/admin/users'
    | '/admin/vocabulary'
    | '/lesson/$id'
    | '/admin/'
    | '/category/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/board'
    | '/chat'
    | '/daily'
    | '/review'
    | '/settings'
    | '/shop'
    | '/stats'
    | '/admin/answers'
    | '/admin/categories'
    | '/admin/languages'
    | '/admin/lessons'
    | '/admin/questions'
    | '/admin/users'
    | '/admin/vocabulary'
    | '/lesson/$id'
    | '/'
    | '/admin'
    | '/category/$id'
  id:
    | '__root__'
    | '/admin'
    | '/_app'
    | '/_app/board'
    | '/_app/chat'
    | '/_app/daily'
    | '/_app/review'
    | '/_app/settings'
    | '/_app/shop'
    | '/_app/stats'
    | '/admin/answers'
    | '/admin/categories'
    | '/admin/languages'
    | '/admin/lessons'
    | '/admin/questions'
    | '/admin/users'
    | '/admin/vocabulary'
    | '/lesson/$id'
    | '/_app/'
    | '/admin/'
    | '/_app/category/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LessonIdRoute: typeof LessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/board': {
      id: '/_app/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof AppBoardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/daily': {
      id: '/_app/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof AppDailyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shop': {
      id: '/_app/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AppShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stats': {
      id: '/_app/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/answers': {
      id: '/admin/answers'
      path: '/answers'
      fullPath: '/admin/answers'
      preLoaderRoute: typeof AdminAnswersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/languages': {
      id: '/admin/languages'
      path: '/languages'
      fullPath: '/admin/languages'
      preLoaderRoute: typeof AdminLanguagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/lessons': {
      id: '/admin/lessons'
      path: '/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AdminLessonsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/vocabulary': {
      id: '/admin/vocabulary'
      path: '/vocabulary'
      fullPath: '/admin/vocabulary'
      preLoaderRoute: typeof AdminVocabularyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/lesson/$id': {
      id: '/lesson/$id'
      path: '/lesson/$id'
      fullPath: '/lesson/$id'
      preLoaderRoute: typeof LessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/category/$id': {
      id: '/_app/category/$id'
      path: '/category/$id'
      fullPath: '/category/$id'
      preLoaderRoute: typeof AppCategoryIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAnswersRoute: typeof AdminAnswersRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminLanguagesRoute: typeof AdminLanguagesRoute
  AdminLessonsRoute: typeof AdminLessonsRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVocabularyRoute: typeof AdminVocabularyRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnswersRoute: AdminAnswersRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminLanguagesRoute: AdminLanguagesRoute,
  AdminLessonsRoute: AdminLessonsRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVocabularyRoute: AdminVocabularyRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppRouteChildren {
  AppBoardRoute: typeof AppBoardRoute
  AppChatRoute: typeof AppChatRoute
  AppDailyRoute: typeof AppDailyRoute
  AppReviewRoute: typeof AppReviewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShopRoute: typeof AppShopRoute
  AppStatsRoute: typeof AppStatsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCategoryIdRoute: typeof AppCategoryIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBoardRoute: AppBoardRoute,
  AppChatRoute: AppChatRoute,
  AppDailyRoute: AppDailyRoute,
  AppReviewRoute: AppReviewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShopRoute: AppShopRoute,
  AppStatsRoute: AppStatsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCategoryIdRoute: AppCategoryIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LessonIdRoute: LessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
